# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3f500bb5247db33e3cdbeb1219a7fba7f3972cd5ed5fad79b63c0625225d30654f562ebe35f91fd5597abeda149086168e2356e2c4290bc9853833c6a8a0bb7

test:
  secret_key_base: 43ffba297732c53a63a099b41a44694f30a2de6aa955954b6ab04089898fe71e09475b8da7eff85329137c1b49c8c8024f141471a5041fd04b17b13e34aababb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
